# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GMqRDv-ST-kbWZCBK190iT3zsijrxV8T
"""

# Import necessary libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Set the style for seaborn
sns.set(style="whitegrid")

# Mount Google Drive (if necessary)
# from google.colab import drive
# drive.mount('/content/drive')

# Load the dataset (update the path if needed)
# df = pd.read_csv('/content/drive/My Drive/netflix_titles.csv')  # Change the path if you uploaded the file elsewhere
df = pd.read_csv('https://raw.githubusercontent.com/kristadofo1/Website/main/netflix_titles.csv')

# Display the first few rows
print("First few rows of the dataset:")
print(df.head())

# Check for missing values
print("\nMissing values in the dataset:")
print(df.isnull().sum())

# Handle missing values
df['director'].fillna('Unknown', inplace=True)
df['cast'].fillna('Unknown', inplace=True)
df['country'].fillna('Unknown', inplace=True)
df['date_added'].fillna('January 1, 2000', inplace=True)

# Convert 'date_added' to datetime format using errors='coerce'
df['date_added'] = pd.to_datetime(df['date_added'], errors='coerce')

# Verify the changes
print("\nDataset information after handling missing values:")
print(df.info())

# 4.1 Distribution of Content Types
plt.figure(figsize=(10, 5))
sns.countplot(data=df, x='type', palette='viridis')
plt.title('Distribution of Content Types on Netflix')
plt.xlabel('Content Type')
plt.ylabel('Count')
plt.show()

# 4.2 Trend of Content Over the Years
df['year_added'] = df['date_added'].dt.year
content_by_year = df.groupby(['year_added', 'type']).size().unstack().fillna(0)

plt.figure(figsize=(14, 7))
content_by_year.plot(kind='line', marker='o', ax=plt.gca())
plt.title('Trend of Movies and TV Shows Added to Netflix Over the Years')
plt.xlabel('Year Added')
plt.ylabel('Count')
plt.grid(True)
plt.show()

# 4.3 Genre Analysis
df['genres'] = df['listed_in'].str.split(', ')
genres_df = df.explode('genres')
genre_counts = genres_df['genres'].value_counts()

plt.figure(figsize=(12, 8))
sns.barplot(y=genre_counts.index[:20], x=genre_counts.values[:20], palette='coolwarm')
plt.title('Top 20 Genres on Netflix')
plt.xlabel('Count')
plt.ylabel('Genre')
plt.show()

# 4.4 Country-Specific Content
df['countries'] = df['country'].str.split(', ')
countries_df = df.explode('countries')
country_counts = countries_df['countries'].value_counts().head(20)

plt.figure(figsize=(12, 8))
sns.barplot(y=country_counts.index, x=country_counts.values, palette='magma')
plt.title('Top 20 Countries by Content on Netflix')
plt.xlabel('Count')
plt.ylabel('Country')
plt.show()

# Additional Visualization 1: Ratings Distribution
plt.figure(figsize=(12, 6))
sns.countplot(data=df, y='rating', palette='Set2', order=df['rating'].value_counts().index)
plt.title('Distribution of Ratings on Netflix')
plt.xlabel('Count')
plt.ylabel('Rating')
plt.show()

# Additional Visualization 2: Duration Distribution for Movies
df_movies = df[df['type'] == 'Movie']
df_movies['duration'] = df_movies['duration'].str.replace(' min', '')

# Handle missing values in 'duration' and convert to integer
df_movies['duration'] = df_movies['duration'].fillna('0').astype(int)

plt.figure(figsize=(12, 6))
sns.histplot(df_movies['duration'], bins=30, kde=True, color='blue')
plt.title('Distribution of Movie Durations on Netflix')
plt.xlabel('Duration (minutes)')
plt.ylabel('Frequency')
plt.show()

# Additional Visualization 3: TV Show Seasons Distribution
df_tv_shows = df[df['type'] == 'TV Show']
df_tv_shows['seasons'] = df_tv_shows['duration'].str.replace(' Season', '').str.replace('s', '')

# Handle missing values in 'seasons' and convert to integer
df_tv_shows['seasons'] = df_tv_shows['seasons'].fillna('0').astype(int)

plt.figure(figsize=(12, 6))
sns.countplot(data=df_tv_shows, x='seasons', palette='Set1', order=sorted(df_tv_shows['seasons'].unique()))
plt.title('Distribution of TV Show Seasons on Netflix')
plt.xlabel('Number of Seasons')
plt.ylabel('Count')
plt.show()

# Conclusion
print("\nConclusion:")
print("1. Distribution of Content Types: Netflix offers more movies than TV shows.")
print("2. Trend of Content Over the Years: There has been a significant increase in the number of movies and TV shows added to Netflix, especially in recent years.")
print("3. Genre Analysis: Certain genres like Dramas, Comedies, and Documentaries are more prevalent.")
print("4. Country-Specific Content: The majority of Netflix content comes from a few key countries, with the USA leading.")
print("5. Ratings Distribution: The most common ratings are TV-MA and TV-14.")
print("6. Movie Durations: Most movies have durations between 80 to 100 minutes.")
print("7. TV Show Seasons: Most TV shows have only one season.")